language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
  - make build-docker test-docker
before_deploy:
  - make dist prep-bintray-json
deploy:
  provider: bintray
  skip_cleanup: true
  file: _scripts/ci/bintray-ci.json
  user: deis-admin
  key:
    secure: "0mBQPzihkk9g9pdIzR7hBsaRWY/RBZ8344Ba34GxNrdAsH3ujTgmP1ExAcyUkOSp6t5eWgVqMkxs45N1weFgtcZkgK2OdX8hHktI33ZMl3tdf2zfzNSHihFl2e0YioBLrQ4Xi/QY9Qincm1mH56o18THaDddyhYx1gMkC26y/d5wxfQ3MIHWRct1UrV2oWTi7kMkY8V/JHDv7iLPZkn0TsBd18b6DDkscrnbIoR1SDJjRdciMutraKtIteKilDVdBhufry+MeA9T/7Td+uAhY/jyzn9ufA7OOWlBmWZiPYvy97W81gWh7Xce1DqOsk7G4l+NNPkSt/hinKRiS2l9QQSXSyMZ1yMrcDR8664+bQORkvL9PulZQC5GXp+HTMU/D1VKGZ/T7+cLSrkbqYjUcNtg0x0HmIPB42WumUcuedMu28TgqP63HotKTxiow0zqEBh/jFEdBNC7iYVvoFMDz/Gf4FmaSCND9QZjSD1dsJNCdbVRC7S2xBcvKx4Myv+2TGsBQAAGRwvIvaj3xZ0jgAIiUDj9NBpBSSm87fqsp5sbOFua4Q2o5KiBFu1vvpkINhCyYV/KNS6m63rBdfZShAv9Uurbxh3bUadbBNePtfU6lXcy65brxW9u0ZbhT1FSisTd5pvH9vI+/lBDoVOUuXbq5gQpYj56W9qu2x2Zcak="
  on:
    branch: master
